babymall/urls.py
from django.conf.urls import url
from . import views
app_name = 'babymall'
urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^commodity/$', views.commodity, name='commodity'),
    url(r'^commoditys/(\d+)/$', views.commoditys, name='commoditys'),


    url(r'^buytoday/$', views.buytodau, name='buytoday'),
    url(r'^information/$', views.information, name='information'),
    url(r'^about/$', views.about, name='about'),

    url(r'^login/$', views.login, name='login'),
    url(r'^loginout/$', views.loginout, name='loginout'),

    url(r'^register/$', views.register, name='register'),

    url(r'^shopcart/(\d+)/$', views.shopcart, name='shopcart'),
    url(r'^details/(\d+)/$', views.details, name='details'),
    url(r'^shopcase/(\d+)/$', views.shopcase, name='shopcase'),

    url(r'^deleone/(\d+)$', views.deleone, name='deleone'),
    url(r'^deleall/$', views.deleall, name='deleall'),

    # 验证码路由
    url(r'^verify/$', views.verify, name='verify'),
]

infant/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include('babymall.urls', namespace='babymall')),
    url(r'search/', include('haystack.urls')),
]

babymall/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Classify(models.Model):
    title = models.CharField(max_length=20, verbose_name='大类别')
    def __str__(self):
        return self.title

    class Meta():
        verbose_name = '大分类'
        verbose_name_plural = verbose_name


class Classifys(models.Model):
    title = models.CharField(max_length=20, verbose_name='小类别')
    title_id = models.ForeignKey(Classify, default=None,  null=True, blank=True, on_delete=models.CASCADE)
    def __str__(self):
        return self.title

    class Meta():
        verbose_name = '小分类'
        verbose_name_plural = verbose_name



class Commodity(models.Model):
    img = models.ImageField(upload_to='img', verbose_name='商品图')
    title = models.CharField(max_length=50, verbose_name='标题')
    ciur_pic = models.SmallIntegerField(verbose_name='现价')
    ori_pic = models.SmallIntegerField(verbose_name='活动价', default=None)
    nub = models.IntegerField(default=0, verbose_name='已售数量')
    discount = models.CharField(max_length=20, default=10, verbose_name='打折')
    cla_id = models.ForeignKey(Classifys, on_delete=models.CASCADE)
    data = models.DateTimeField(auto_now_add=True, verbose_name='上架时间')

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = '商品'
        verbose_name_plural = verbose_name




class Case(models.Model):
    img = models.ImageField(upload_to='img', verbose_name='商品图')
    title = models.CharField(max_length=50, verbose_name='标题')
    data = models.DateTimeField(auto_now_add=True, verbose_name='发表时间')
    detail = models.CharField(max_length=200, verbose_name='内容')

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = '资讯'
        verbose_name_plural = verbose_name


class MyUser(User):
    phone = models.IntegerField(verbose_name='电话')

    def __str__(self):
        return self.username

    class Meta():
        verbose_name = '用户'
        verbose_name_plural = verbose_name


class Shop(models.Model):
    img = models.ImageField(upload_to='img', verbose_name='商品图')
    title = models.CharField(max_length=50, verbose_name='标题')
    color = models.CharField(max_length=20, verbose_name='颜色')
    num = models.IntegerField(default=1, verbose_name='购买数量')
    price = models.SmallIntegerField(verbose_name='单价')
    subtotal = models.SmallIntegerField(verbose_name='小计')
    user_id = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    def __str__(self):
        return self.title

    class Meta():
        verbose_name = '购物车'
        verbose_name_plural = verbose_name




class Color(models.Model):
    color1 = models.CharField(max_length=20, verbose_name='颜色1', default=None)
    color2 = models.CharField(max_length=20, verbose_name='颜色2', default=None)
    color3 = models.CharField(max_length=20, verbose_name='颜色3', default=None)
    color4 = models.CharField(max_length=20, verbose_name='颜色4', default=None)
    com_id = models.ForeignKey(Commodity, verbose_name='商品外键', on_delete=models.CASCADE)

    def __str__(self):
        return self.color1

    class Meta():
        verbose_name = '颜色'
        verbose_name_plural = verbose_name

templates/base.html
{% load extend_fun %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>母婴商城</title>
{#    <link rel="stylesheet" href="/static/css/bootstrap.min.css">#}
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
{#    <script src="/static/js/bootstrap.min.js"></script>#}
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>

  <link rel="stylesheet" type="text/css" href="/static/css/main.css">
  <link rel="stylesheet" type="text/css" href="/static/layui/css/layui.css">
  <script type="text/javascript" src="/static/layui/layui.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
</head>
<body id="list-cont">

  <div class="site-nav-bg">
    <div class="site-nav w1200">
      <p class="sn-back-home">
        <i class="layui-icon layui-icon-home"></i>
        <a href="{% url 'babymall:index' %}">首页</a>
      </p>
      <div class="sn-quick-menu">

          {% if request.user.username %}
              {% getshopcart request.user as count %}
              {% getsuer request.user as sid %}
              <div class="login"><a href="{% url 'babymall:login' %}">用户：{{ request.user }}</a></div>
              <div class="login" ><a style="color: #0C0C0C" href="{% url 'babymall:loginout' %}">退出</a></div>
              <div class="sp-cart"><a style="color: #ff5500" href="{% url 'babymall:shopcart' sid%}">购物车：</a><span>{{ count }}</span></div>

          {% else%}
              <div class="login"><a href="{% url 'babymall:login' %}">登录</a></div>
              <div class="login"><a href="{% url 'babymall:register' %}">注册</a></div>
          {% endif %}

          {% block login %}
          {% endblock %}



      </div>
    </div>
  </div>



  <div class="header">
    <div class="headerLayout w1200">
      <div class="headerCon">
        <h1 class="mallLogo">
          <a href="#" title="母婴商城">
            <img src="/static/img/logo.png" alt="">
          </a>
        </h1>
        <div class="mallSearch">
          <form action="/search/" class="layui-form" method="get" novalidate>
            <input type="search" name="q" required   autocomplete="off" class="layui-input" placeholder="请输入需要的商品">
            <button class="layui-btn" type="submit" >
                <i class="layui-icon layui-icon-search"></i>
            </button>
            <input type="hidden" name="" value="">
          </form>
        </div>
      </div>
    </div>
  </div>


  <div class="content content-nav-base commodity-content buytoday-content information-content about-content datails-content login-content shopcart-content">
  <div id="list-cont">
    <div class="main-nav">
      <div class="inner-cont0">
        <div class="inner-cont1 w1200">
          <div class="inner-cont2">
            <a href="{% url 'babymall:commodity' %}" class="active">所有商品</a>
            <a href="{% url 'babymall:buytoday' %}">今日团购</a>
            <a href="{% url 'babymall:information' %}">母婴资讯</a>
            <a href="{% url 'babymall:about' %}">关于我们</a>
          </div>
        </div>
      </div>
    </div>
    {% block body %}

    {% endblock %}
  </div>
  </div>
 <div class="footer">
    <div class="ng-promise-box">
      <div class="ng-promise w1200">
        <p class="text">
          <a class="icon1" href="javascript:">7天无理由退换货</a>
          <a class="icon2" href="javascript:">满99元全场免邮</a>
          <a class="icon3" style="margin-right: 0" href="javascript:">100%品质保证</a>
        </p>
      </div>
    </div>
    <div class="mod_help w1200">
      <p>
        <a href="{% url 'babymall:about' %}">关于我们</a>
        <span>|</span>
        <a href="#">帮助中心</a>
        <span>|</span>
        <a href="#">售后服务</a>
        <span>|</span>
        <a href="{% url 'babymall:information' %}">母婴资讯</a>
        <span>|</span>
        <a href="#">关于货源</a>
      </p>
      <p class="coty">母婴商城版权所有 &copy; 2012-2020 More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>
    </div>
  </div>
{% block scr %}
{% endblock %}
</body>
</html>

templates/commodity.html
{% extends 'base.html' %}
{% load extend_fun %}
{% block body %}
<div class="commod-cont-wrap">
      <div class="commod-cont w1200 layui-clear">
        <div class="left-nav">
          <div class="title">所有分类</div>
          <div class="list-box">
            {% for c in cla %}
                <dl>
                    {% getcomid c.id as clss %}
                 <dt>{{ c.title }}</dt>
                    {% for b in clss.classifys_set.all %}
                        <dd><a href="{% url 'babymall:commoditys' b.id %}">{{ b.title }}</a></dd>
                    {% endfor %}

                </dl>
            {% endfor %}

          </div>
        </div>
        <div class="right-cont-wrap">
          <div class="right-cont">
            <div class="sort layui-clear">
              <a class="active" href="javascript:" >销量</a>
              <a href="javascript:" >价格</a>
              <a href="javascript:" >新品</a>
              <a href="javascript:" >收藏</a>
            </div>
            <div class="prod-number">
              <span>{{ num }}个商品</span>
            </div>
            <div class="cont-list layui-clear" id="list-cont">
                {% if page %}
                {% for c in com %}
                    <div class="item">
                        <div class="img">
                          <a href="{% url 'babymall:details' c.id%}"><img src="/static/media/{{ c.img }}" style="width: 280px; height: 280px" alt=""></a>
                        </div>
                        <div class="text">
                          <p class="title">{{ c.title }}</p>
                          <p class="price">
                            <span class="pri">￥{{ c.ciur_pic }}</span>
                            <span class="nub">{{ c.nub }}付款</span>
                          </p>
                        </div>
                      </div>
                {% endfor %}
                {% endif %}

            </div>
            <!-- 模版引擎导入 -->

{#            <div id="demo0" style="text-align: center;"></div>#}
            <div class="pagination" style="text-align: center; margin: 0 0 0 0; ">
                <ul style="font-family: 'Lato', sans-serif;">
                    {% if page.has_previous %}
                        <li><a href="{{ page.parms }}?page={{ page.previous_page_number }}">上一页</a></li>
                    {% endif %}
                    {% for num in paginator.page_range %}
                        <li><a href="{{ page.parms }}?page={{ num }}">{{ num }}</a></li>
                    {% endfor %}
                    {% if page.has_next %}
                        <li><a href="{{ page.parms }}?page={{ page.next_page_number }}">下一页</a></li>
                    {% endif %}
                </ul>
            </div>
          </div>
        </div>
      </div>
</div>
{% endblock %}

{% block scr %}
<script>

  layui.config({
    base: '/static/js/util/' //你存放新模块的目录，注意，不是layui的模块目录
  }).use(['mm','laypage','jquery'],function(){
      var laypage = layui.laypage,$ = layui.$,
     mm = layui.mm;
       laypage.render({
        elem: 'demo0'
        ,count: 100 //数据总数
      });


    $('.sort a').on('click',function(){
      $(this).addClass('active').siblings().removeClass('active');
    });
    $('.list-box dt').on('click',function(){
      if($(this).attr('off')){
        $(this).removeClass('active').siblings('dd').show();
        $(this).attr('off','')
      }else{
        $(this).addClass('active').siblings('dd').hide();
        $(this).attr('off',true)
      }
    })

});
</script>
{% endblock %}

templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="data-cont-wrap w1200">
      <div class="crumb">
        <a href="{% url 'babymall:index' %}">首页</a>
        <span>></span>
        <a href="{% url 'babymall:commodity' %}">所有商品</a>
        <span>></span>
        <a href="{% url 'babymall:details' com.id %}">产品详情</a>
      </div>
      <div class="product-intro layui-clear">
        <div class="preview-wrap">
          <a href="#"><img src="/static/{{ com.img }}" style="width: 400px; height: 400px" alt=""></a>
        </div>
        <div class="itemInfo-wrap">
          <div class="itemInfo">
            <div class="title">
              <h4>{{ com.title }}</h4>
              <span><i class="layui-icon layui-icon-rate-solid"></i>收藏</span>
            </div>
            <div class="summary">
              <p class="reference"><span>参考价</span> <del>￥{{ com.ori_pic }}.00</del></p>
              <p class="activity"><span>活动价</span><strong class="price"><i>￥</i>{{ com.ciur_pic }}.00</strong></p>
              <p class="address-box"><span>送&nbsp;&nbsp;&nbsp;&nbsp;至</span><strong class="address">江西&nbsp;&nbsp;南昌&nbsp;&nbsp;东湖区</strong></p>
            </div>
            <div class="choose-attrs">
              <div class="color layui-clear"><span class="title">颜&nbsp;&nbsp;&nbsp;&nbsp;色</span> <div class="color-cont"><span class="btn">白色</span> <span class="btn active">粉丝</span></div></div>
              <div class="number layui-clear"><span class="title">数&nbsp;&nbsp;&nbsp;&nbsp;量</span>
                  <div class="number-cont">

                  <form action="{% url 'babymall:shopcase' com.id %}" method="post" style="display:block; float: left">
                      {% csrf_token %}
                      <span class="cut btn">-</span>
                        <input  maxlength="4" type="text" name="num" value="{{ a }}">
                      <span class="add btn">+</span>
                       <div class="choose-btns" >
                            <a href=""><button class="layui-btn layui-btn-primary purchase-btn">立刻购买</button></a>
                            <button class="layui-btn  layui-btn-danger car-btn"><i class="layui-icon layui-icon-cart-simple"></i>加入购物车</button>
                        </div>
                  </form>

                       {% if messages %}
                            <script>
                                {% for msg in messages %}
                                    alert('{{ msg.message }}');
                                {% endfor %}
                            </script>
                        {% endif %}

                  </div>
              </div>
            </div>

          </div>
        </div>
      </div>
      <div class="layui-clear">
        <div class="aside">
          <h4>热销推荐</h4>
          <div class="item-list">
            <div class="item">
              <img src="/static/img/details_img2.jpg">
              <p><span>可爱宝宝粉色连体秋裤</span><span class="pric">￥99.00</span></p>
            </div>
            <div class="item">
              <img src="/static/img/details_img2.jpg">
              <p><span>可爱宝宝粉色连体秋裤</span><span class="pric">￥99.00</span></p>
            </div>
            <div class="item">
              <img src="/static/img/details_img2.jpg">
              <p><span>可爱宝宝粉色连体秋裤</span><span class="pric">￥99.00</span></p>
            </div>
            <div class="item">
              <img src="/static/img/details_img2.jpg">
              <p><span>可爱宝宝粉色连体秋裤</span><span class="pric">￥99.00</span></p>
            </div>
            <div class="item">
              <img src="/static/img/details_img2.jpg">
              <p><span>可爱宝宝粉色连体秋裤</span><span class="pric">￥99.00</span></p>
            </div>
            <div class="item">
              <img src="/static/img/details_img2.jpg">
              <p><span>可爱宝宝粉色连体秋裤</span><span class="pric">￥99.00</span></p>
            </div>
          </div>
        </div>
        <div class="detail">
          <h4>详情</h4>
          <div class="item">
            <img src="/static/img/details_imgbig.jpg">
          </div>
        </div>
      </div>
    </div>
{% endblock %}
{% block scr %}
<script type="text/javascript">

  layui.config({
    base: '/static/js/util/' //你存放新模块的目录，注意，不是layui的模块目录
  }).use(['mm','jquery'],function(){
      var mm = layui.mm,$ = layui.$;
      var cur = $('.number-cont input').val();
      $('.number-cont .btn').on('click',function(){
        if($(this).hasClass('add')){
          cur++;

        }else{
          if(cur > 1){
            cur--;
          }
        }
        $('.number-cont input').val(cur)
      })

  });
</script>
{% endblock %}

templates/index.html
{% load extend_fun %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <link rel="stylesheet" type="text/css" href="/static/css/main.css">
  <link rel="stylesheet" type="text/css" href="/static/layui/css/layui.css">
  <script type="text/javascript" src="/static/layui/layui.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
</head>
<body id="list-cont">
  <div class="site-nav-bg">
    <div class="site-nav w1200">
      <p class="sn-back-home">
        <i class="layui-icon layui-icon-home"></i>
        <a href="{% url 'babymall:index' %}">首页</a>
      </p>
      <div class="sn-quick-menu">


          {% if request.user.username %}
              {% getshopcart request.user as count %}
              {% getsuer request.user as sid %}
              <div class="login"><a href="{% url 'babymall:login' %}">用户：{{ request.user }}</a></div>
              <div class="login" ><a style="color: #0C0C0C" href="{% url 'babymall:loginout' %}">退出</a></div>
              <div class="sp-cart"><a style="color: #ff5500" href="{% url 'babymall:shopcart' sid %}">购物车：</a><span>{{ count }}</span></div>

          {% else%}
              <div class="login"><a href="{% url 'babymall:login' %}">登录</a></div>
              <div class="login"><a href="{% url 'babymall:register' %}">注册</a></div>
          {% endif %}


          {% block login %}
          {% endblock %}




      </div>
    </div>
  </div>


  <div class="header">
    <div class="headerLayout w1200">
      <div class="headerCon">
        <h1 class="mallLogo">
          <a href="#" title="母婴商城">
            <img src=" /static/img/logo.png">
          </a>
        </h1>
        <div class="mallSearch">
          <form action="/search/" class="layui-form" method="get" novalidate>
            <input type="search" name="q" required   autocomplete="off" class="layui-input" placeholder="请输入需要的商品">
            <button class="layui-btn" type="submit" >
                <i class="layui-icon layui-icon-search"></i>
            </button>
            <input type="hidden" name="" value="">
          </form>
        </div>
      </div>
    </div>
  </div>


  <div class="content">
    <div class="main-nav">
      <div class="inner-cont0">
        <div class="inner-cont1 w1200">
          <div class="inner-cont2">
            <a href="{% url 'babymall:commodity' %}" class="active">所有商品</a>
            <a href="{% url 'babymall:buytoday' %}">今日团购</a>
            <a href="{% url 'babymall:information' %}">母婴资讯</a>
            <a href="{% url 'babymall:about' %}">关于我们</a>
          </div>
        </div>
      </div>
    </div>
    <div class="category-con">
      <div class="category-inner-con w1200">
        <div class="category-type">
          <h3>全部分类</h3>
        </div>
        <div class="category-tab-content">
          <div class="nav-con">
            <ul class="normal-nav layui-clear">

                {% for l1 in com %}
                    <li class="nav-item">
                        <div class="title">{{ l1.title }}</div>
                        <p>
                        {% getcomid l1.id as clss %}
                        {% for l2 in clss.classifys_set.all %}
                            <a href="">{{ l2.title }}</a>
                        {% endfor %}
                        </p>
                        <i class="layui-icon layui-icon-right"></i>
                      </li>
                {% endfor %}

            </ul>
          </div>
        </div>
      </div>
      <div class="category-banner">
        <div class="w1200">
          <img src=" /static/img/banner1.jpg" alt="">
        </div>
      </div>
    </div>
    <div class="floors">
      <div class="sk">
        <div class="sk_inner w1200">
          <div class="sk_hd">
            <a href="javascript:">
              <img src=" /static/img/s_img1.jpg" alt="">
            </a>
          </div>
          <div class="sk_bd">
            <div class="layui-carousel" id="test1">
              <div carousel-item>
                <div class="item-box">
                  {% for com in com1 %}
                    <div class="item">
                        <a href="{% url 'babymall:details' com.id %}"><img src=" /static/media/{{ com.img }}" alt=""></a>
                        <div class="title">{{ com.title }}</div>
                        <div class="price">
                          <span>￥{{ com.ori_pic }}.00</span>
                          <del>￥{{ com.ciur_pic }}.00</del>
                        </div>
                    </div>
                  {% endfor %}
                </div>
                <div class="item-box">
                  {% for com in com2 %}
                    <div class="item">
                        <a href="{% url 'babymall:details' com.id %}"><img src=" /static/media/{{ com.img }}" alt=""></a>
                        <div class="title">{{ com.title }}</div>
                        <div class="price">
                          <span>￥{{ com.ori_pic }}.00</span>
                          <del>￥{{ com.ciur_pic }}.00</del>
                        </div>
                    </div>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>






    <div class="hot-recommend-con">
      <div class="tlinks">Collect from <a href="http://www.cssmoban.com/" >网页模板</a></div>
       <div class="hot-con1 w1200 layui-clear">
          <div class="item">
            <h4>热销推荐</h4>
            <div class="big-img">
              <a href="javascript:"><img src=" /static/img/hot1.png"></a>
            </div>
            <div class="small-img">
              <a href="javascript:"><img src=" /static/img/hot2.png" alt=""></a>
            </div>
          </div>
          <div class="item">
            <div class="top-img">
              <a href="javascript:"><img src="/static/img/hot5.jpg"></a>
            </div>
            <div class="bottom-img">
              <a href="javascript:"><img src="/static/img/hot6.jpg"></a>
              <a class="baby-cream" href="javascript:;"><img src="/static/img/hot7.jpg"></a>
            </div>
          </div>
          <div class="item item1 margin0 padding0">
            <a href="javascript:"><img src=" /static/img/hot8.jpg"></a>
            <a href="javascript:"><img class="btm-img" src=" /static/img/hot9.jpg"></a>
          </div>
      </div>
    </div>



    <div class="product-cont w1200" id="product-cont">
      <div class="product-item product-item1 layui-clear">
        <div class="left-title">
          <h4><i>1F</i></h4>
          <img src="/static/img/icon_gou.png">
          <h5>宝宝服饰</h5>
        </div>
        <div class="right-cont">
          <a href="javascript:;" class="top-img"><img src=" /static/img/img12.jpg" alt=""></a>
          <div class="img-box">
            <a href="javascript:;"><img src=" /static/img/s_img7.jpg"></a>
            <a href="javascript:;"><img src=" /static/img/s_img8.jpg"></a>
            <a href="javascript:;"><img src=" /static/img/s_img9.jpg"></a>
            <a href="javascript:;"><img src=" /static/img/s_img10.jpg"></a>
            <a href="javascript:;"><img src=" /static/img/s_img11.jpg"></a>
          </div>
        </div>
      </div>
      <div class="product-item product-item2 layui-clear">
        <div class="left-title">
          <h4><i>2F</i></h4>
          <img src="/static/img/icon_gou.png">
          <h5>奶粉辅食</h5>
        </div>
        <div class="right-cont">
          <a href="javascript:;" class="top-img"><img src=" /static/img/img12.jpg" alt=""></a>
          <div class="img-box">
            <a href="javascript:;"><img src=" /static/img/s_img7.jpg"></a>
            <a href="javascript:;"><img src=" /static/img/s_img8.jpg"></a>
            <a href="javascript:;"><img src=" /static/img/s_img9.jpg"></a>
            <a href="javascript:;"><img src=" /static/img/s_img10.jpg"></a>
            <a href="javascript:;"><img src=" /static/img/s_img11.jpg"></a>
          </div>
        </div>
      </div>
      <div class="product-item product-item3 layui-clear">
        <div class="left-title">
          <h4><i>3F</i></h4>
          <img src="/static/img/icon_gou.png">
          <h5>宝宝用品</h5>
        </div>
        <div class="right-cont">
          <a href="javascript:;" class="top-img"><img src="/static/img/img12.jpg" alt=""></a>
          <div class="img-box">
            <a href="javascript:;"><img src="/static/img/s_img7.jpg"></a>
            <a href="javascript:;"><img src="/static/img/s_img8.jpg"></a>
            <a href="javascript:;"><img src="/static/img/s_img9.jpg"></a>
            <a href="javascript:;"><img src="/static/img/s_img10.jpg"></a>
            <a href="javascript:;"><img src="/static/img/s_img11.jpg"></a>
          </div>
        </div>
      </div>
    </div>

    <div class="product-list-box" id="product-list-box">
      <div class="product-list-cont w1200">
        <h4>更多推荐</h4>
        <div class="product-item-box layui-clear">
          {% for com in com2  %}
             <div class="list-item">
            <a href="{% url 'babymall:details' com.id %}"><img src="/static/media/{{ com.img }}" alt="" style=" width: 160px; height: 160px"></a>
            <p>{{ com.title }}</p>
            <span>￥{{ com.ciur_pic }}.00</span>
          </div>
          {% endfor %}



          </div>
        </div>
      </div>
    </div>


  <div class="footer">
    <div class="ng-promise-box">
      <div class="ng-promise w1200">
        <p class="text">
          <a class="icon1" href="javascript:">7天无理由退换货</a>
          <a class="icon2" href="javascript:">满99元全场免邮</a>
          <a class="icon3" style="margin-right: 0" href="javascript:">100%品质保证</a>
        </p>
      </div>
    </div>
    <div class="mod_help w1200">
      <p>
        <a href="javascript:;">关于我们</a>
        <span>|</span>
        <a href="javascript:;">帮助中心</a>
        <span>|</span>
        <a href="javascript:;">售后服务</a>
        <span>|</span>
        <a href="javascript:;">母婴资讯</a>
        <span>|</span>
        <a href="javascript:;">关于货源</a>
      </p>
      <p class="coty">母婴商城版权所有 &copy; 2012-2020 More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>
    </div>
  </div>
  <script type="text/javascript">

layui.config({
    base: '/static/js/util/' //你存放新模块的目录，注意，不是layui的模块目录
  }).use(['mm','carousel'],function(){
      var carousel = layui.carousel,
     mm = layui.mm;
     var option = {
        elem: '#test1'
        ,width: '100%' //设置容器宽度
        ,arrow: 'always'
        ,height:'298'
        ,indicator:'none'
      };
      carousel.render(option);
      // 模版引擎导入
     // var ins = carousel.render(option);
     // var html = demo.innerHTML;
     // var listCont = document.getElementById('list-cont');
     // // console.log(layui.router("#/about.html"))
     //  mm.request({
     //    url: '../json/index.json',
     //    success : function(res){
     //      console.log(res)
     //      listCont.innerHTML = mm.renderHtml(html,res)
     //      ins.reload(option);
     //    },
     //    error: function(res){
     //      console.log(res);
     //    }
     //  })


});
  </script>
</body>
</html>